const db = require('../models');
const { hash } = require('../utils/crypt');

const seedUsers = () => new Promise(resolve => (
  db.User.bulkCreate([
    {
      email: 'ben@gmail.com',
      first_name: 'Ben',
      last_name: 'Octopus',
      password: '12345',
      age_range: 1,
      credit_rating: 700,
      address_1: '620 2nd Street',
      city: 'San Francisco',
      state: 'CA',
      zip: '94107',
    },
    {
      email: 'david@gmail.com',
      first_name: 'David',
      last_name: 'Blanchard',
      password: '12345',
      age_range: 1,
      credit_rating: 700,
      address_1: '1001 Pine St',
      city: 'San Francisco',
      state: 'CA',
      zip: '94107',
    },
    {
      email: 'james@gmail.com',
      first_name: 'Jim',
      last_name: 'Chambers',
      password: '12345',
      age_range: 1,
      credit_rating: 700,
      address_1: '1445 Bush St',
      city: 'San Francisco',
      state: 'CA',
      zip: '94107',
    },
    {
      email: 'anna@gmail.com',
      first_name: 'Anna',
      last_name: 'Beyonce',
      password: '12345',
      age_range: 1,
      credit_rating: 700,
      address_1: '7 3rd St',
      city: 'San Francisco',
      state: 'CA',
      zip: '94107',
    },
    {
      email: 'sevil@gmail.com',
      first_name: 'Sevil',
      last_name: 'Rao',
      password: '12345',
      age_range: 1,
      credit_rating: 700,
      address_1: '640 2nd St',
      city: 'San Francisco',
      state: 'CA',
      zip: '94107',
    },
    {
      email: 'alice@gmail.com',
      first_name: 'Alice',
      last_name: 'Teddy',
      password: '12345',
      age_range: 1,
      credit_rating: 700,
      address_1: '2225 23rd St',
      city: 'San Francisco',
      state: 'CA',
      zip: '94107',
    },
    {
      email: 'rai@gmail.com',
      first_name: 'Rai',
      last_name: 'Man',
      password: '12345',
      age_range: 1,
      credit_rating: 700,
      address_1: '151 3rd St',
      city: 'San Francisco',
      state: 'CA',
      zip: '94107',
    },
    {
      email: 'emma@gmail.com',
      first_name: 'Emma',
      last_name: 'Tyae',
      password: '12345',
      age_range: 1,
      credit_rating: 700,
      address_1: '620 2nd St',
      city: 'San Francisco',
      state: 'CA',
      zip: '94107',
    },
    {
      email: 'coop@gmail.com',
      first_name: 'Coop',
      last_name: 'Substitutian',
      password: '12345',
      age_range: 1,
      credit_rating: 700,
      address_1: '170 O\'Farrel St.',
      city: 'San Francisco',
      state: 'CA',
      zip: '94107',
    },
    {
      email: 'berkeley@gmail.com',
      first_name: 'Berk',
      last_name: 'Enstocks',
      password: '12345',
      age_range: 1,
      credit_rating: 700,
      address_1: '160 Main St.',
      city: 'San Francisco',
      state: 'CA',
      zip: '94107',
    },
    {
      email: 'test@test.com',
      first_name: 'Berk',
      last_name: 'Enstocks',
      password: hash('Pass1!'),
      age_range: 1,
      credit_rating: 700,
      address_1: '160 Main St.',
      city: 'San Francisco',
      state: 'CA',
      zip: '94107',
    },
    {
      email: 'fogell@gmail.com',
      first_name: 'Fogell',
      last_name: 'McLovin',
      password: '12345',
      age_range: 1,
      credit_rating: 560,
      address_1: '100 W Glenoaks Blvd',
      city: 'Glendale',
      state: 'CA',
      zip: '91202',
    },
    {
      email: 'seth@gmail.com',
      first_name: 'Seth',
      last_name: 'Hill',
      password: '12345',
      age_range: 1,
      credit_rating: 500,
      address_1: '1118 E Colorado St',
      city: 'Glendale',
      state: 'CA',
      zip: '91205',
    },
    {
      email: 'evan@gmail.com',
      first_name: 'Evan',
      last_name: 'Rogen',
      password: '12345',
      age_range: 1,
      credit_rating: 500,
      address_1: '100 W Glenoaks Blvd',
      city: 'Glendale',
      state: 'CA',
      zip: '91202',
    },
    {
      email: 'jules@gmail.com',
      first_name: 'Jules',
      last_name: 'Stone',
      password: '12345',
      age_range: 1,
      credit_rating: 750,
      address_1: '548 Market St',
      city: 'San Francisco',
      state: 'CA',
      zip: '94104',
    },
    {
      email: 'greg@gmail.com',
      first_name: 'Greg',
      last_name: 'Mottola',
      password: '12345',
      age_range: 1,
      credit_rating: 647,
      address_1: '901 Mission St',
      city: 'San Francisco',
      state: 'CA',
      zip: '94103',
    },
    {
      email: 'evan1@gmail.com',
      first_name: 'Evan',
      last_name: 'Goldberg',
      password: '12345',
      age_range: 1,
      credit_rating: 735,
      address_1: '680 2nd St',
      city: 'San Francisco',
      state: 'CA',
      zip: '94107',
    },
    {
      email: 'bill@gmail.com',
      first_name: 'Bill',
      last_name: 'Slater',
      password: '12345',
      age_range: 1,
      credit_rating: 680,
      address_1: '338 Main St',
      city: 'San Francisco',
      state: 'CA',
      zip: '94105',
    },
    {
      email: 'michael@gmail.com',
      first_name: 'Michael',
      last_name: 'Cera',
      password: '12345',
      age_range: 1,
      credit_rating: 734,
      address_1: '145 Buchanan St',
      city: 'San Francisco',
      state: 'CA',
      zip: '94102',
    },
    {
      email: 'judd@gmail.com',
      first_name: 'Judd',
      last_name: 'Apatow',
      password: '12345',
      age_range: 1,
      credit_rating: 720,
      address_1: '1520 Taylor St',
      city: 'San Francisco',
      state: 'CA',
      zip: '94133',
    },
    {
      email: 'joe@gmail.com',
      first_name: 'Joe',
      last_name: 'Lo Truglio',
      password: '12345',
      age_range: 1,
      credit_rating: 700,
      address_1: '4039 Jim Rosa Lane',
      city: 'San Francisco',
      state: 'CA',
      zip: '94103',
    },
    {
      email: 'martha@gmail.com',
      first_name: 'Martha',
      last_name: 'MacIsaac',
      password: '12345',
      age_range: 1,
      credit_rating: 700,
      address_1: '1860 Ellis St',
      city: 'San Francisco',
      state: 'CA',
      zip: '94115',
    },
    {
      email: 'ben@gmail.com',
      first_name: 'Ben',
      last_name: 'Octopus',
      password: '12345',
      age_range: 1,
      credit_rating: 700,
      address_1: '620 2nd Street',
      city: 'San Francisco',
      state: 'CA',
      zip: '94107',
    },
    {
      email: 'elias@gmail.com',
      first_name: 'Elias',
      last_name: 'Jewel',
      password: '12345',
      age_range: 1,
      credit_rating: 756,
      address_1: '886 Noe St',
      city: 'San Francisco',
      state: 'CA',
      zip: '94114',
    },
    {
      email: 'angela@gmail.com',
      first_name: 'Angela',
      last_name: 'Beck',
      password: '12345',
      age_range: 1,
      credit_rating: 730,
      address_1: '190 Cervantes Blvd',
      city: 'San Francisco',
      state: 'CA',
      zip: '94123',
    },
    {
      email: 'risto@gmail.com',
      first_name: 'Risto',
      last_name: 'Jardine',
      password: '12345',
      age_range: 1,
      credit_rating: 690,
      address_1: '801 Avalon Ave',
      city: 'San Francisco',
      state: 'CA',
      zip: '94112',
    },
  ], {})
    .then(entries => resolve(entries.map(User => User.dataValues.id)))
    .catch((err) => { throw new Error(err); })
));

const seedHosts = userIds => new Promise(resolve => (
  db.Host.bulkCreate([
    {
      user_id: userIds.pop(),
      total_store_length: 500,
      total_store_width: 600,
      s_address_1: '620 2nd St',
      s_city: 'San Francisco',
      s_state: 'CA',
      s_zip: 94107,
      rental_rate: 3000,
      image_url: '/api/img/bagelshop.jpg'
    },
    {
      user_id: userIds.pop(),
      total_store_length: 2000,
      total_store_width: 3000,
      s_address_1: '1001 Pine St',
      s_city: 'San Francisco',
      s_state: 'CA',
      s_zip: 94103,
      rental_rate: 5000,
      image_url: '/api/img/Car.jpg'
    },
    {
      user_id: userIds.pop(),
      total_store_length: 800,
      total_store_width: 600,
      s_address_1: '4400 Shellmound St',
      s_city: 'Emneryville',
      s_state: 'CA',
      s_zip: 94609,
      rental_rate: 7500,
      image_url: '/api/img/commercial.jpeg'
    },
    {
      user_id: userIds.pop(),
      total_store_length: 10000,
      total_store_width: 20000,
      s_address_1: '5095 Telegraph Ave Suite',
      s_city: 'Oakland',
      s_state: 'CA',
      s_zip: 94102,
      rental_rate: 10000,
      image_url: '/api/img/formal.jpeg'
    },
    {
      user_id: userIds.pop(),
      total_store_length: 400,
      total_store_width: 300,
      s_address_1: '450 10th St',
      s_city: 'San Francisco',
      s_state: 'CA',
      s_zip: 94103,
      rental_rate: 1200,
      image_url: '/api/img/Fashion.jpg'
    },
    {
      user_id: userIds.pop(),
      total_store_length: 700,
      total_store_width: 600,
      s_address_1: '2300 16th St',
      s_city: 'San Francisco',
      s_state: 'CA',
      s_zip: 94107,
      rental_rate: 2500,
      image_url: '/api/img/garage.jpg'
    },
    {
      user_id: userIds.pop(),
      total_store_length: 3000,
      total_store_width: 2000,
      s_address_1: '448 Grove St',
      s_city: 'San Francisco',
      s_state: 'CA',
      s_zip: 94102,
      rental_rate: 5600,
      image_url: '/api/img/homeliving.jpg'
    },
    {
      user_id: userIds.pop(),
      total_store_length: 1000,
      total_store_width: 600,
      s_address_1: '2211 Filbert St',
      s_city: 'San Francisco',
      s_state: 'CA',
      s_zip: 94123,
      rental_rate: 6400,
      image_url: '/api/img/Modern.jpeg'
    },
    {
      user_id: userIds.pop(),
      total_store_length: 7000,
      total_store_width: 6000,
      s_address_1: '3001 Lyon St',
      s_city: 'San Francisco',
      s_state: 'CA',
      s_zip: 94123,
      rental_rate: 9000,
      image_url: '/api/img/sportsshop.jpeg'
    },
    {
      user_id: userIds.pop(),
      total_store_length: 150,
      total_store_width: 350,
      s_address_1: '291 Geary St',
      s_city: 'San Francisco',
      s_state: 'CA',
      s_zip: 94102,
      rental_rate: 1000,
      image_url: '/api/img/workshop.jpeg'
    },
    {
      user_id: userIds.pop(),
      total_store_length: 450,
      total_store_width: 700,
      s_address_1: '847-849 Santiago St',
      s_city: 'San Francisco',
      s_state: '94116',
      s_zip: 94107,
      rental_rate: 2500,
      image_url: '/api/img/trendy_store.jpg'
    },
    {
      user_id: userIds.pop(),
      total_store_length: 350,
      total_store_width: 740,
      s_address_1: '966 Geneva Ave',
      s_city: 'San Francisco',
      s_state: 'CA',
      s_zip: 94112,
      rental_rate: 2500,
      image_url: '/api/img/gift_shop.jpg'
    },
    {
      user_id: userIds.pop(),
      total_store_length: 1000,
      total_store_width: 600,
      s_address_1: '3366 Pierce St',
      s_city: 'San Francisco',
      s_state: 'CA',
      s_zip: 94123,
      rental_rate: 5000,
      image_url: '/api/img/yellow_shop.jpg'
    },
    {
      user_id: userIds.pop(),
      total_store_length: 400,
      total_store_width: 700,
      s_address_1: '2146 Union St',
      s_city: 'San Francisco',
      s_state: 'CA',
      s_zip: 94123,
      rental_rate: 3100,
      image_url: '/api/img/bagel_shop.jpg'
    },
    {
      user_id: userIds.pop(),
      total_store_length: 550,
      total_store_width: 640,
      s_address_1: '653 Minna St',
      s_city: 'San Francisco',
      s_state: 'CA',
      s_zip: 94103,
      rental_rate: 3000,
      image_url: '/api/img/perfume_shop.jpg'
    },
    {
      user_id: userIds.pop(),
      total_store_length: 350,
      total_store_width: 500,
      s_address_1: '20 Pinehurst Way',
      s_city: 'San Francisco',
      s_state: 'CA',
      s_zip: 94127,
      rental_rate: 4000,
      image_url: '/api/img/arts_crafts.jpg'
    },
    {
      user_id: userIds.pop(),
      total_store_length: 390,
      total_store_width: 600,
      s_address_1: '220 Lathrop Ave',
      s_city: 'San Francisco',
      s_state: 'CA',
      s_zip: 94134,
      rental_rate: 2500,
      image_url: '/api/img/shoe_store.jpg'
    },
    {
      user_id: userIds.pop(),
      total_store_length: 500,
      total_store_width: 600,
      s_address_1: '653 Noe St',
      s_city: 'San Francisco',
      s_state: 'CA',
      s_zip: 94114,
      rental_rate: 2500,
      image_url: '/api/img/jewelry_store.jpg'
    },
  ], {})
    .then(() => resolve())
    .catch((err) => { throw new Error(err); })
));

const seedRenters = userids => new Promise(resolve => (
  db.Renter.bulkCreate([
    {
      user_id: userids.pop(),
    },
    {
      user_id: userids.pop(),
    },
    {
      user_id: userids.pop(),
    },
    {
      user_id: userids.pop(),
    },
    {
      user_id: userids.pop(),
    },
    {
      user_id: userids.pop(),
    },
    {
      user_id: userids.pop(),
    },
    {
      user_id: userids.pop(),
    },
    {
      user_id: userids.pop(),
    },
    {
      user_id: userids.pop(),
    },
    {
      user_id: userids.pop(),
    },
    {
      user_id: userids.pop(),
    },
    {
      user_id: userids.pop(),
    },
    {
      user_id: userids.pop(),
    },
    {
      user_id: userids.pop(),
    },
    {
      user_id: userids.pop(),
    },
    {
      user_id: userids.pop(),
    },
    {
      user_id: userids.pop(),
    },
  ], {})
    .then(() => resolve())
    .catch((err) => { throw new Error(err); })
));

module.exports = async () => {
  const userIds = await seedUsers();
  console.log('userids:', userIds.length);
  await seedHosts([...userIds]);
  await seedRenters([...userIds]);
};
